### PR TITLE
fix: implement Symbol.hasInstance for cross-library instanceof checks

### LINKED ISSUE #61: [JS] Fix instanceof or move away from instanceof within arrow-js
### Describe the enhancement requested

There are a number of places that arrow's js package uses `instanceof`.  For example:

```
// from table.ts in the Table constructor
if (args[0] instanceof Schema) {
    schema = args.shift() as Schema<T>;
}
```

Unfortunately, this is quite brittle.  This will fail whenever a library ends up with multiple instances of the arrow library.  For example:

 * LanceDb currently uses arrow version 14.  If the calling user is using any other version of arrow then node will happily install two versions of arrow and the checks will fail. (also, these failures tend to be very opaque)
 * Even if the user is using the exact same version of arrow there are cases where two instances of arrow are created.  For example, our users using vite have run into https://github.com/vitejs/vite/issues/3910

I would argue that some of the core types (at least `Schema` but maybe also `Table` / `Vector` / `RecordBatch` too) should be considered stable and users should be allowed to have different versions / instances.  We tried working around this in lancedb by declaring arrow a peer dependency and that solves the first bullet above but it's also somewhat unconventional (for javascript) and inconvenient for our users (they are forced to use whatever version of arrow we are using and when we change our arrow version it is a breaking change).

This is not critical, we've worked around this by re-building the schema if the input from our user looks like a schema, but I wanted to see if other JS users/maintainers felt similarly and, if so, I might try and find some time to explore a fix.

Some potential fixes:

 * Add methods like `isArrowSchema` and use those methods instead of `instanceof`
 * Customize the definition of `instanceof` by implementing https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/hasInstance on types like `Schema`.
 * Stick with the current but upstream methods like https://github.com/lancedb/lancedb/blob/dfc518b8fbc5920cf7dafd072335257be1e5d9c5/nodejs/lancedb/sanitize.ts#L491 so that this kind of "schema rebuild" is maintained here in arrow.

### Component(s)

JavaScript

### PR DESCRIPTION
**Pull request by Divyanshu-s13**
What's Changed
Fixed the instanceof check issue that occurs when multiple versions or instances of the Arrow library are loaded in the same application. Previously, checks like [value instanceof Schema] would fail if the value came from a different Arrow library instance (e.g., when a library like LanceDB uses a different Arrow version than the user's code).

Now instanceof works reliably across different Arrow library instances by using global symbols for type identification.

Also added helper functions like [isArrowSchema()],[isArrowTable()], etc. for explicit type checking.

Closes #61.

### CODE REVIEW

**Comment by Divyanshu-s13** [comment]
@kou  I’ve fixed the issue. Could you please merge it?

**Comment by kou** [comment]
Could you add tests for this?

**Comment by Divyanshu-s13** [comment]
> Could you add tests for this?

I have added a test for this.

File: src/data.ts [hunk 1]
```diff
@@ -41,6 +41,9 @@ export interface Buffers<T extends DataType> {
     [BufferType.TYPE]: T['TArray'];
 }
 
+/** @ignore */
+const kDataSymbol = Symbol.for('apache-arrow/Data');
```
Comment (domoritz) [inline src/data.ts:45]: This is a good solution. We just need to make sure to not accidentally use `Symbol()` instead of `Symbol.for` since the former does not create unique instances.

**Review by domoritz — APPROVED** [review]
Very nice.

* I wonder whether we can do some kind of check whether a second instance of arrow exists. We could show a warning. Otherwise I'd worry that we will at some point run into issues where people have multiple versions of Arrow in their systems for a long time. 
* What's the performance impact of these changes? This needs to be addressed before we can merge the changes.

**Review by domoritz — CHANGES_REQUESTED** [review]
See request for a perf analysis. We have benchmarks in this repo in https://github.com/apache/arrow-js/tree/main/perf.

**Comment by Divyanshu-s13** [comment]
@domoritz  Could you please let me know if any further changes are needed, or if this is ready to merge?

**Comment by Divyanshu-s13** [comment]
@kou @domoritz ??

**Comment by kou** [comment]
@trxcllnt Do you want to review this before we merge this?

**Comment by kou** [comment]
Thanks.
