### PR TITLE
fix: interval MonthDayNano precision loss when reading JSON-encoded int64s

### LINKED ISSUE #15: Occasional Integration test failure
On a PR I got what seemed to be an occasional unrelated error in the integration tests between Javascript and C++:
https://github.com/apache/arrow/actions/runs/15113644177/job/42478772147#step:11:20082

If you expand the failure, you get the following logs:
```
  ################# FAILURES #################
  FAILED TEST: interval_mdn C++ producing,  JS consuming
  <class 'RuntimeError'>: Command failed: /build/js/bin/integration.ts -a /tmp/tmp9z_g9id9/4b71e8dd_generated_interval_mdn.json_as_file -j /tmp/arrow-integration-da8j13w3/generated_interval_mdn.json --mode VALIDATE
  With output:
  --------------
  
   json: /tmp/arrow-integration-da8j13w3/generated_interval_mdn.json
  arrow: /tmp/tmp9z_g9id9/4b71e8dd_generated_interval_mdn.json_as_file
  Error: json and arrow record batches report the same values: fail 
   Error: 4: -1109815901,1503025502,1803493504,261723424 !== -1109815901,1503025502,1803493496,261723424
      at file:///build/js/bin/integration.ts:216:23
      at compareVectors (file:///build/js/bin/integration.ts:219:7)
      at file:///build/js/bin/integration.ts:191:13
      at compareTableIsh (file:///build/js/bin/integration.ts:193:7)
      at validateReaderIntegration (file:///build/js/bin/integration.ts:147:13)
      at validate (file:///build/js/bin/integration.ts:134:5)
      at async file:///build/js/bin/integration.ts:59:21
      at validateReaderIntegration (file:///build/js/bin/integration.ts:150:15)
      at validate (file:///build/js/bin/integration.ts:134:5)
      at async file:///build/js/bin/integration.ts:59:21
  
  --------------
  
  
  FAILED TEST: interval_mdn JS producing,  C++ consuming
  <class 'RuntimeError'>: Command failed: /build/cpp/debug/arrow-json-integration-test --integration --arrow=/tmp/tmp9z_g9id9/847e76a4_generated_interval_mdn.json_as_file --json=/tmp/arrow-integration-da8j13w3/generated_interval_mdn.json --mode=VALIDATE
  With output:
  --------------
  Error message: Invalid: Record batch 1 did not match
  JSON:
  f1:   [
      null,
      null,
      -1233922984M1832700302d3945364585489654316ns,
      -865764767M-1868167704d5995137276854357748ns,
      -1109815901M1503025502d1124093548480635000ns,
      null,
      -1853878757M-470410382d-3482109426864569063ns,
      -274343993M150680692d1713410614578950687ns,
      null,
      1204985559M1793434370d37200152077710886ns
    ]
  
  Arrow:
  f1:   [
      null,
      null,
      -1233922984M1832700302d3945364585489654316ns,
      -865764767M-1868167704d5995137276854357748ns,
      -1109815901M1503025502d1124093548480635008ns,
      null,
      -1853878757M-470410382d-3482109426864569063ns,
      -274343993M150680692d1713410614578950687ns,
      null,
      1204985559M1793434370d37200152077710886ns
    ]
```

And the explanation seems to be limited floating-point precision when the value `-1109815901M1503025502d1124093548480635000ns` is read from the JSON file. The nanoseconds components is `1124093548480635000` in the JSON, but Javascript only knows floating-point numbers and they don't have enough precision for this large integer. The nanoseconds component is therefore rounded to `1124093548480635008`, and that fails comparing to the data received over Arrow IPC.

### PR DESCRIPTION
**Pull request by GeorgeLeePatterson**
## Summary

This PR fixes precision handling for `IntervalMonthDayNano` nanoseconds when reading JSON, and aligns the tests with the actual behavior across build targets.

## Changes

- Switched JSON parsing in `src/util/json.ts` from `json-bignum` to `json-with-bigint` with native `BigInt` output.
- Removed post-parse unsafe-integer normalization logic that could not recover precision once rounded.
- Updated `test/unit/vector/interval-month-day-nano-tests.ts` to:
  - assert parsed nanoseconds are `bigint`,
  - include the additional `expect(vec.get(0)).toStrictEqual(array)` assertion.

## Validation

Ran locally:

- `yarn lint:ci`
- `yarn test`

Closes #15.

### CODE REVIEW

File: src/util/json.ts [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+
+// @ts-ignore
+import { parse as bignumJSONParse, BigNumber } from 'json-bignum';
+
+/** @ignore */
+export function parseArrowJSON(source: string): any {
+    return normalizeUnsafeIntegers(bignumJSONParse(source));
+}
+
+function normalizeUnsafeIntegers(value: any): any {
```
Comment (pitrou) [inline src/util/json.ts]: Can you add a comment explaining the rationale as you did in the PR description?

File: src/util/json.ts [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+    if (typeof value === 'number') {
+        if (Number.isInteger(value) && !Number.isSafeInteger(value)) {
```
Comment (pitrou) [inline src/util/json.ts]: So this would be for values such as `100000000000000000`? Should this be reported as a bug in `json-bignum`?

Comment (pitrou) [reply src/util/json.ts]: Oops, I see that library is unmaintained. If there is a better replacement, perhaps we should just switch to that?

Comment (pitrou) [reply src/util/json.ts]: Ok, it seems https://www.npmjs.com/package/json-bigint calls `Number.isSafeInteger` correctly (and also can produce native JS `BigInt` instead of a home-grown type).

File: test/unit/vector/interval-month-day-nano-tests.ts [hunk 3]
```diff
@@ -77,4 +78,39 @@ describe(`MonthDayNanoIntervalVector`, () => {
...
+            '-390122861233460600',
+            '6684525287992311000'
+        ];
+        for (const sample of samples) {
+            const nanoseconds = Number.parseFloat(sample);
+            expect(`${nanoseconds}`).toBe(sample);
+            const obj: Partial<IntervalMonthDayNanoObject> = { nanoseconds };
+            const array = toIntervalMonthDayNanoInt32Array([obj]);
+            const vec = makeIntervalMonthDayNanoVector(array);
+            expect(vec.type).toBeInstanceOf(IntervalMonthDayNano);
```
Comment (pitrou) [inline test/unit/vector/interval-month-day-nano-tests.ts:92]: Should we also call `expect(vec.get(0)).toStrictEqual(array);` as above?

File: test/unit/vector/interval-month-day-nano-tests.ts [hunk 4]
```diff
@@ -77,4 +78,39 @@ describe(`MonthDayNanoIntervalVector`, () => {
...
         expect(toIntervalMonthDayNanoObjects(vec.get(0), false)).toStrictEqual([{ ...EMPTY_INTERVAL_MONTH_DAY_NANO_OBJECT, ...obj }]);
     });
+
+    test(`Unsafe integer nanoseconds parsed as numbers roundtrip correctly`, () => {
+        const samples = [
+            '-390122861233460600',
+            '6684525287992311000'
+        ];
+        for (const sample of samples) {
+            const nanoseconds = Number.parseFloat(sample);
```
Comment (pitrou) [inline test/unit/vector/interval-month-day-nano-tests.ts]: This seems incorrect since that will introduce FP inaccuracies. You need something like `BigInt(sample)`.

For example `console.log(BigInt(Number.parseFloat("-390122861233460600")));` gives me `-390122861233460608n`.

File: src/util/json.ts (hunk 2 above)
Comment (GeorgeLeePatterson) [reply src/util/json.ts]: Good catch

File: test/unit/vector/interval-month-day-nano-tests.ts (hunk 4 above)
Comment (GeorgeLeePatterson) [reply test/unit/vector/interval-month-day-nano-tests.ts]: Another good catch. I'll get these shored up.

File: src/util/interval.ts [hunk 5]
```diff
@@ -46,7 +46,11 @@ export function toIntervalMonthDayNanoInt32Array(objects: Partial<IntervalMonthD
         data[ai++] = interval['days'] ?? 0;
         const nanoseconds = interval['nanoseconds'];
         if (nanoseconds) {
-            const ns = BigInt(nanoseconds);
+            // Avoid BigInt(number) for unsafe integers, which can embed
+            // IEEE-754 rounding before conversion.
```
Comment (pitrou) [inline src/util/interval.ts]: Is this still any useful? I don't understand why ```BigInt(`${nanoseconds}`)``` would be any better than `BigInt(nanoseconds)`. If the data is already rounded, we cannot restore the lost precision...

What we could do is call `nanoseconds.isSafeInteger` and warn/assert if it returns false?

File: test/unit/vector/interval-month-day-nano-tests.ts [hunk 6]
```diff
@@ -77,4 +78,42 @@ describe(`MonthDayNanoIntervalVector`, () => {
...
     });
+
+    test(`Unsafe integer nanoseconds represented as bigint roundtrip correctly`, () => {
+        const samples = [
+            '-390122861233460600',
+            '6684525287992311000'
+        ];
+        for (const sample of samples) {
+            const nanoseconds = BigInt(sample);
+            const obj: Partial<IntervalMonthDayNanoObject> = { nanoseconds };
```
Comment (pitrou) [inline test/unit/vector/interval-month-day-nano-tests.ts:89]: Is the right field being populated here, or should that be `{ nanoseconds : nanoseconds }`? Sorry, not a TS developer.

Comment (GeorgeLeePatterson) [reply test/unit/vector/interval-month-day-nano-tests.ts:89]: Has the same effect when the key name and variable name are the same.

Comment (pitrou) [reply test/unit/vector/interval-month-day-nano-tests.ts:89]: I see, thanks.

File: src/util/interval.ts (hunk 5 above)
Comment (GeorgeLeePatterson) [reply src/util/interval.ts]: Had a chance to review, and you are correct. I will fix and update shortly.

File: src/util/json.ts [hunk 7]
```diff
@@ -0,0 +1,28 @@
...
+// software distributed under the License is distributed on an
+// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+// KIND, either express or implied.  See the License for the
+// specific language governing permissions and limitations
+// under the License.
+
+// @ts-ignore
+import jsonBigInt from 'json-bigint';
+
+const parseJSON = jsonBigInt({ useNativeBigInt: true }).parse;
```
Comment (trxcllnt) [inline src/util/json.ts]: Should we use `useNativeBigInt: true` here? From the [Note on native BigInt support](https://www.npmjs.com/package/json-bigint#note-on-native-bigint-support) section of the readme, it seems BigInts are converted to JS Numbers, which doesn't seem correct?

From the description it seems we might want to set `storeAsString: true` instead, since we're more concerned about accuracy, not trying to infer the value type based on the representation in the data. For example, we know the values in the IntervalMonthDayYear `DATA` array are 64-bit signed integers, regardless whether they're stored as strings in the JSON. Thoughts?

Comment (pitrou) [reply src/util/json.ts]: > From the [Note on native BigInt support](https://www.npmjs.com/package/json-bigint#note-on-native-bigint-support) section of the readme, it seems BigInts are converted to JS Numbers, which doesn't seem correct?

I read this as: on the serialization path, a JS BigInt is serialized as a [JSON number](https://datatracker.ietf.org/doc/html/rfc8259#section-6).

[The example](https://www.npmjs.com/package/json-bigint#optionsusenativebigint-boolean-default-false) shows that parsing doesn't lose precision.

**Comment by pitrou** [comment]
> I just looked at the `json-bigint` commit history and issues. Seems like it may be similarly un-maintained? [This issue](https://github.com/sidorares/json-bigint/issues/99) mentions alternatives.

Ahah, the joys of the JavaScript ecosystem...

File: src/util/json.ts (hunk 7 above)
Comment (trxcllnt) [reply src/util/json.ts]: The serialization part makes sense, but I was concerned about this:
```js
o !== JSONbig.parse(JSONbig.stringify(o))
```

It seems like if parse sometimes produces BitInt and other times Number, we'd have to know to always cast the numbers to BigInt after parsing and hope that the values that parsed as numbers didn't lose precision.

That said, I think [this](https://github.com/sidorares/json-bigint/issues/88#issuecomment-1935464056) is a bigger issue. It sounds like we can't `JSONbig.parse()` any payloads that includes decimals, which seems problematic if parsing an ArrowJSON message with both a Float64 and IntervalMonthDayYear column.

Comment (GeorgeLeePatterson) [reply src/util/json.ts]: This is a good point, first a convention based approach will be hard to catch, as you identified. That should be addressed, but ultimately will come down to some level of convention at some point. But that other issue really is the more concerning one. What's the standard way of handling this, I assume vendor-ing their code isn't preferable, but maybe that's the only option?

**Comment by GeorgeLeePatterson** [comment]
Sure, let me note the change in library.

**Comment by kou** [comment]
Thanks. I'll merge this.
